import type { NextPage } from 'next'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from "next-i18next/serverSideTranslations"
import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import styles from '../styles/Home.module.css'
import nextI18NextConfig from '../next-i18next.config.js';

const Home: NextPage = () => {
  const { t } = useTranslation();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          {t('title')}
        </h1>
        <Link
            href='/'
            locale="es"
          >
        <button>es</button>
        </Link>
        <Link
            href='/'
            locale="en"
          >
        <button>en</button>
        </Link>
      </main>
      <footer className={styles.footer}>
        {t('footer')}
      </footer>
    </div>
  )
}

export default Home

export const getServerSideProps = async (context: any) => {
  return { 
    props:{
      ...(await serverSideTranslations(context.locale, ["translation"], nextI18NextConfig, ['en', 'ca']))
    }
  }
}